name: Build and Release WordPress Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Zip plugin and create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Zip plugin folder (with folder inside ZIP)
        run: |
          zip -r health-product-recommender-lite.zip health-product-recommender-lite

      - name: Create GitHub Release and attach ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: health-product-recommender-lite.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
